### ISSUE TITLE
docker-compose.yml sample file

### ISSUE THREAD

**Issue by hermesalvesbr** [tomsik68/docker-xampp#43]
```
version: '3'
services:
  tomsik68:
    container_name: docker-xampp
    image: tomsik68/xampp:7
    ports:
      - "41062:80"
      - "41061:22"
    volumes:
      - "./www:/www"
      - "./mysql/data:/opt/lampp/var/mysql"
      - "./apache:/opt/lampp/apache2/conf.d"
```
