### ISSUE TITLE
Separate mysql socket of mysql data

### ISSUE THREAD

**Issue by sanslash332** [tomsik68/docker-xampp#53]
# Bug Report

I'm running Docker on: wsl

## XAMPP start command

I used the following command to start the xampp container:

```bash
docker stack deploy -c docker-compose.yml xampp
```

I've created a compose file with the following content:

```yaml
version: '3.8'
services:
  xampp:
    image: tomsik68/xampp:7
    ports:
      - 10022:22
      - 10080:80
      - 10443:443
    volumes:
      - "../:/opt/lampp/htdocs"
      # - "~/db:/opt/lampp/var/mysql"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
    logging:
      driver: json-file
      options:
        max-size: 10m
```

OK, more explanation here.

If you read carefulli the compose, you see that the volume for the mysql data is commented.
ON a simple way, this could work without problem; I did see it on other project; if you mount the directory where the database files are plased you can preserve it without a problem. You can use a bind mount like this, or other kind of docker volume to store the data.

The problem is, that on /opt/lampp/var/mysql/ is too the mysql.sock file; the binding socket for stablish mysql connections on the machine. And these kind of files can't be mounted on a volume, so. If you active the volume, and start the container, mysql says that can't find the mysql.sock file and crash instandly, after create the first db files.

So, the solution for this is edit the /opt/lampp/etc/my.cnf config file, and put the mysql.sock file on other location. something like /opt/lampp/var/sockets/.
With that, you can mount your db folder and works without problem. Maybe this change could be as default on the image, to allow people mount the db directory and persist the db data.

I'll check if is easy to do this change on the image to give you a PR :-)

thanks for your work, the image is awesome!
